from typing import TypedDict
from langgraph.graph import StateGraph, END
from src.agents import get_agents
from src.freshdesk_api import add_public_note

class AgentState(TypedDict):
    ticket_id: int
    query: str
    search_results: str
    analysis: str
    summary: str
    customer_message: str
    next_action: str
    error: str | None


def search_node(state: AgentState) -> AgentState:
    """Search Agent: Find similar tickets"""
    print("\nSearch Agent: Analyzing ticket and searching for similar cases...")
    
    agents = get_agents()
    search_agent = agents["search_agent"]
    
    try:
        input_text = state['query']

        result = search_agent.invoke({"input": input_text})
        
        state["search_results"] = result.get("output", "No results found")
        state["next_action"] = "summarize"
        
        print(f"Search Agent: Found relevant context")
        
    except Exception as e:
        print(f"Search Agent Error: {str(e)}")
        state["error"] = f"Search failed: {str(e)}"
        state["next_action"] = "end"
    
    return state


def summarization_node(state: AgentState) -> AgentState:
    """Summarization Agent: Create insights and customer message"""
    print("\nSummarization Agent: Generating insights and customer message...")
    
    agents = get_agents()
    summarization_agent = agents["summarization_agent"]
    
    try:
        # Execute summarization agent
        input_text = f"""Ticket Description: {state['query']}

Similar Tickets Found:
{state['search_results']}

Create a customer-friendly summary with recommended solutions."""

        result = summarization_agent.invoke({"input": input_text})
        
        state["summary"] = result.get("output", "Summary generation failed")
        state["customer_message"] = result.get("output", "")
        state["next_action"] = "post_to_freshdesk"
        
        print(f"Summarization Agent: Summary created")
        
    except Exception as e:
        print(f"Summarization Agent Error: {str(e)}")
        state["error"] = f"Summarization failed: {str(e)}"
        state["next_action"] = "end"
    
    return state


def post_to_freshdesk_node(state: AgentState) -> AgentState:
    """Post summary to Freshdesk ticket"""
    print(f"\nPosting summary to Freshdesk ticket #{state['ticket_id']}...")
    
    try:
        message = f"""{state['customer_message']}\n\n---\n
Note: This response was generated by AI based on similar past tickets."""

        add_public_note(state['ticket_id'], message)
        
        state["next_action"] = "end"
        print(f"Successfully posted to ticket #{state['ticket_id']}")
        
        # Show what was posted
        print("\n" + "="*70)
        print(f"POSTED TO FRESHDESK TICKET #{state['ticket_id']}:")
        print("="*70)
        print(message)
        print("="*70)
        print("\nCheck Freshdesk ticket in the 'Activities' or 'Notes' section")
        
    except Exception as e:
        print(f"Error posting to Freshdesk: {str(e)}")
        state["error"] = f"Failed to post note: {str(e)}"
        state["next_action"] = "end"
    
    return state


def decision_node(state: AgentState) -> str:
    """Route to next step based on state"""
    next_action = state.get("next_action", "end")
    
    if state.get("error"):
        print(f"\nWorkflow error detected: {state['error']}")
        return "end"
    
    return next_action


def create_agent_workflow():
    """Create LangGraph workflow with autonomous agents"""
    workflow = StateGraph(AgentState)
    
    # Add nodes
    workflow.add_node("search", search_node)
    workflow.add_node("summarize", summarization_node)
    workflow.add_node("post_to_freshdesk", post_to_freshdesk_node)
    
    # Set entry point
    workflow.set_entry_point("search")
    
    # Add conditional edges
    workflow.add_conditional_edges(
        "search",
        decision_node,
        {
            "summarize": "summarize",
            "end": END
        }
    )
    
    workflow.add_conditional_edges(
        "summarize",
        decision_node,
        {
            "post_to_freshdesk": "post_to_freshdesk",
            "end": END
        }
    )
    
    workflow.add_conditional_edges(
        "post_to_freshdesk",
        decision_node,
        {
            "end": END
        }
    )
    
    return workflow.compile()


def run_agent_workflow(ticket_id: int, query: str):
    """Execute multi-agent workflow for new ticket"""
    print("\n" + "="*60)
    print(f"Starting Agentic Workflow for Ticket #{ticket_id}")
    print("="*60)
    
    # Initialize state
    initial_state = AgentState(
        ticket_id=ticket_id,
        query=query,
        search_results="",
        analysis="",
        summary="",
        customer_message="",
        next_action="search",
        error=None
    )
    
    # Create and run workflow
    workflow = create_agent_workflow()
    
    try:
        final_state = workflow.invoke(initial_state)
        
        print("\n" + "="*60)
        print("Agentic Workflow Complete!")
        print("="*60)
        
        return final_state
        
    except Exception as e:
        print(f"\nWorkflow execution failed: {str(e)}")
        return {
            **initial_state,
            "error": str(e),
            "next_action": "end"
        }



